language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default

services:
  - xvfb

script: 
  - cd thinking_wt_4_0
  - qmake
  - make
  - ./thinking_wt_4_0 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_4_0
  - cd ..
  - cd thinking_wt_4_1
  - qmake
  - make
  - ./thinking_wt_4_1 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_4_1
  - cd ..
  - cd thinking_wt_4_2
  - qmake
  - make
  - ./thinking_wt_4_2 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_4_2
  - cd ..
  - cd thinking_wt_4_3
  - qmake
  - make
  - ./thinking_wt_4_3 --docroot . --http-address 0.0.0.0 --http-port 8080 &
  - sleep 10
  - sudo killall thinking_wt_4_3
  - cd ..

